### ISSUE TITLE
Question / Problem - Internationalization files getting back to default

### ISSUE THREAD

**Issue by daniemygdio** [ionic-team/ionic-starter-super#113]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Whenever I change a file at i18n I can see the changes in when using ionic serve and it's consistent. When I use ionic cordova run, all the changes in the language files are removed and they go back to the original variables and values.

**Expected behavior:**
Using cordova run wouldn't remove my changes at variables and values in the i18n folder.

**Steps to reproduce:**
Make any changes to, for example, en.json. 
"LIST_MASTER_TITLE": "Itens" > to > "LIST_MASTER_TITLE": "List All Itens" 
Save the file.
Use ionic serve and see the change in the title working.
Use ionic cordova run (android) and then see how the value goes back to "Itens".

Am I missing something? I already deleted all the other files to see how it would behave, but then after running cordova run android, all the language files come back to my source.

**Comment by gslender** [comment]
just delete the folder "www/assets" and then build/run again

**Comment by danielsogl** [comment]
I close this issue because I can't reproduce it. Remove your www folder content and run the build command again.

**Comment by janpio** [comment]
@daniemygdio Where are you editing the i18n files? If you edit directly in `/www` they will be overwritten on every build, which `ionic cordova run` executes as a first step for example. You should edit them in `/src` which will be copied over to `/www` on the build. That way you keep the changes.

**Comment by daniemygdio** [comment]
@janpio that was my problem! so dumb! thank you guys for the attention
