### ISSUE TITLE
Too slow to load ! White screen shows up for 10 seconds even after the splash screen. 

### ISSUE THREAD

**Issue by hemant07rulz** [ionic-team/ionic-starter-super#121]
I have created apps using both Ionic 1 and 2. While I never had any problem with speed using Ionic 1, It has become too slow with Ionic 2 !! 
Is it normal ? I just tested using the tutorial startup app also, deployed it to my device and it hangs for at least 10 seconds before showing the home screen!

I did not change anything to the config.xml file. I am using the ionic 2 super template.

**Comment by janpio** [comment]
How did you build the app? Add the `--prod` parameter.

**Comment by janpio** [comment]
In general: Github issues are for bugs and problems with apps. Your problem seems better suited for the community forum where "chatting" about stuff is normal: https://forum.ionicframework.com/

**Comment by hemant07rulz** [comment]
I added  the --prod parameter. Also doing the same issue with release build. As I have deployed the app to app store

**Comment by janpio** [comment]
Then this is not about the super starter at all? Then you are totally wrong here. Please post at the forum.
