### ISSUE TITLE
Question: Use Lazy Loading For Pages

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-starter-super#122]
I was a bit confused when I used `ionic generate page something` for the first time and it created a `something.module.ts` file. Now I figured out that it is used for [lazy loading](https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w/edit) and was wondering if that should be implemented in this best practice starter?

**Comment by janpio** [comment]
Lazy Loading is not really pinned down yet, but here is a PR for this project that would implement it: https://github.com/ionic-team/ionic-starter-super/pull/110 (Has to be updated to solve some conflicts though)

If you want to implement lazy loading, have a look at the blog posts about it: http://blog.ionic.io/ionic-and-lazy-loading-pt-1/ http://blog.ionic.io/ionic-and-lazy-loading-pt-2/

**Comment by simonhaenisch** [comment]
I already implemented it ([this](http://blog.angular-university.io/angular2-ngmodule/) was very helpful), was just wondering why it's not in here yet. Thanks for the clarification :).

**Comment by danielsogl** [comment]
Lazy loading is now enabled by default
