### ISSUE TITLE
Animal List Misses Albert Albatros

### ISSUE THREAD

**Issue by daixtrose** [ionic-team/ionic-starter-super#130]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The demo app shows a list of animals:
- Burt Bear
- Charlie Cheetah
- Donald Duck
- etc.

**Expected behavior:**

The list should begin with **Albert Albatros**

**Steps to reproduce:**

```cmd
ionic start super
cd super
ionic serve
```

**Comment by janpio** [comment]
Feel free to submit a PR: https://github.com/ionic-team/ionic-starter-super/blob/43d6d53aa3a9c47077874843c7e4699de34967e2/src/mocks/providers/items.ts#L18
(and a source...)

**Comment by mlynch** [comment]
This made me laugh, thanks :D
