### ISSUE TITLE
Broken template due to erroneous commit

### ISSUE THREAD

**Issue by machour** [ionic-team/ionic-starter-super#131]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently I cannot run this starter, I'm seeing this error:
```
[18:22:51]  typescript: src/pages/map/map.ts, line: 51
            ';' expected.

      L51:      create new marker;
      L52:       let markerOptions: MarkerOptions = {
```

**Expected behavior:**
ionic serve should start the app.

**Steps to reproduce:**
```shell
ionic start superIonic super
cd superIonic
ionic serve
```

**Other information:**
The error was introduced in last commit, which uncommented a lot of code (by mistake I guess):
https://github.com/ionic-team/ionic-starter-super/commit/b75cf773e430da0f1d4837926b064448bc9f88cb#diff-0394c7a4036fa2097aa67156fa084e9dR51

**Ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v8.4.0
    npm  : 5.3.0
    OS   : macOS Sierra
```

**Comment by koficypher** [comment]
experiencing the same issue

Ionic info:

Ionic Framework: 3.6.1
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3

**Comment by danielsogl** [comment]
Fixed!
