### ISSUE TITLE
add function enableProdMode

### ISSUE THREAD

**Issue by davidgv88** [ionic-team/ionic-starter-super#141]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Angular is running in the development mode. Call enableProdMode() to enable the production mode.

**Expected behavior:**

This template could add the function "enableProdMode" commented
And uncomment when needed.

**Comment by janpio** [comment]
enableProdMode is automatically enabled by the Ionic build process (via Ionic app-scripts) if you do a production build (`--prod`). No need to do anything.
